# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curator', models.CharField(default=None, max_length=64)),
                ('question', models.TextField(default=None, max_length=90)),
                ('customer_name', models.CharField(default=None, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
