# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 15:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=64)),
                ('preview', models.TextField(blank=True, default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=4, null=True, verbose_name='Важность')),
                ('is_main', models.BooleanField(default=False, verbose_name='Выводить на главную')),
                ('is_slide', models.BooleanField(default=False, verbose_name='Выводить на слайдер')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('news', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки новостей',
            },
        ),
    ]
