# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=None, max_length=64)),
                ('item_price', models.DecimalField(decimal_places=0, default=None, max_digits=10)),
                ('item_time', models.CharField(default=None, max_length=64)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Позиции прайса',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default=None, max_length=64)),
            ],
            options={
                'verbose_name': 'Блок услуг или исследований',
                'verbose_name_plural': 'Блоки услуг или исследований',
            },
        ),
        migrations.AddField(
            model_name='pricelist',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
