# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_auto_20180301_1922'),
        ('service', '0007_auto_20180301_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Позиция прайса', 'verbose_name_plural': 'Позиции прайса'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Блок услуг или исследований', 'verbose_name_plural': 'Блоки услуг или исследований'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='department',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
