# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20180301_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
