# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, max_length=24),
        ),
    ]
