# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64)),
                ('short_name', models.CharField(default='Кардиология', max_length=24)),
                ('description', models.TextField(default=None)),
                ('image', models.ImageField(default=None, null=True, upload_to='department_images/')),
                ('icon', models.ImageField(default=None, null=True, upload_to='department_images/')),
                ('services_description', models.TextField(default=None)),
                ('consult_price', models.DecimalField(decimal_places=0, default=None, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
    ]
