# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20180227_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='is_active',
            new_name='is_index_active',
        ),
    ]
