# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20180228_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(default='Кардиология', max_length=24, unique=True),
        ),
    ]
