# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20180301_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
