# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_auto_20180301_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
